import React from 'react';
// import PropTypes from 'prop-types';

class Introduction extends React.PureComponent {
  render() {
    return (
      <section>
        <h2 className="section-title">Introduction</h2>
        <p>
          From the moment of its birth, a star is engaged in an internal,
          unrelenting struggle. Crushing gravitational forces press inward,
          opposing the outward push of hot gas generated by nuclear fusion deep
          in the core. For most of a star’s lifetime these two forces are
          equally balanced, but at certain moments one force gets stronger or
          weaker, causing profound changes in the star.
        </p>
        <p>
          A star’s physical properties—its size, temperature, color, and
          brightness—are the product of the star’s initial mass and this clash
          of forces, and these physical properties change during a star’s
          lifetime.
        </p>
      </section>
    );
  }
}

// Introduction.propTypes = {
//   menuOpen: PropTypes.bool,
//   handleClick: PropTypes.func,
//   handleClose: PropTypes.func,
// };

export default Introduction;
